// <auto-generated />
using Family_Roots.DAL.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_Roots.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250329154217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdoptingParents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatePlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatePlaceId");

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.DatePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatePlaces");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.DatePlaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DatePlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DatePlaceId");

                    b.HasIndex("PersonId");

                    b.ToTable("DatePlaceEntities");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DatePlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DatePlaceId");

                    b.HasIndex("PersonId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdoptedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaptizedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuriedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeathId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GEDId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GraduationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdoptedId");

                    b.HasIndex("BaptizedId");

                    b.HasIndex("BirthId");

                    b.HasIndex("BuriedId");

                    b.HasIndex("DeathId");

                    b.HasIndex("GraduationId");

                    b.HasIndex("LastAddressId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Adoption", b =>
                {
                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "DatePlace")
                        .WithMany()
                        .HasForeignKey("DatePlaceId");

                    b.Navigation("DatePlace");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Contact", b =>
                {
                    b.HasOne("Family_Roots.DAL.Store.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.DatePlaceEntity", b =>
                {
                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "DatePlace")
                        .WithMany()
                        .HasForeignKey("DatePlaceId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("DatePlace");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Event", b =>
                {
                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "DatePlace")
                        .WithMany()
                        .HasForeignKey("DatePlaceId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("DatePlace");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Family_Roots.DAL.Store.Entities.Person", b =>
                {
                    b.HasOne("Family_Roots.DAL.Store.Entities.Adoption", "Adopted")
                        .WithMany()
                        .HasForeignKey("AdoptedId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "Baptized")
                        .WithMany()
                        .HasForeignKey("BaptizedId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "Birth")
                        .WithMany()
                        .HasForeignKey("BirthId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "Buried")
                        .WithMany()
                        .HasForeignKey("BuriedId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "Death")
                        .WithMany()
                        .HasForeignKey("DeathId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.DatePlace", "Graduation")
                        .WithMany()
                        .HasForeignKey("GraduationId");

                    b.HasOne("Family_Roots.DAL.Store.Entities.Address", "LastAddress")
                        .WithMany()
                        .HasForeignKey("LastAddressId");

                    b.Navigation("Adopted");

                    b.Navigation("Baptized");

                    b.Navigation("Birth");

                    b.Navigation("Buried");

                    b.Navigation("Death");

                    b.Navigation("Graduation");

                    b.Navigation("LastAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
