<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Family_Roots</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GeneGenie.Gedcom" Version="1.0.3" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WatsonORM.Sqlite" Version="3.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GedcomParser">
      <HintPath>..\..\..\GedcomParser\src\GedcomParser\bin\Release\net6\GedcomParser.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
